---
- name: configure an Automation Controller
  hosts: localhost
  gather_facts: false
  vars_files: vars.yml
  tasks:
  - name: Add inventory INV-CAC-AC
    ansible.controller.inventory: 
      name: "INV-CAC-AC"
      description: "configure an Automation Controller - Automation Controller"
      organization: "Default"
      state: present

  - name: Add host to inventory INV-CAC-AC
    ansible.controller.host:
      name: "{{ automation_controller_host }}"
      description: "Automation Controller"
      inventory: "INV-CAC-AC"
      state: present

  - name: Create job template to add host in inventory
    ansible.controller.job_template:
      name: JOB-ADD-HOST-INVENTORY
      job_type: "run"
      organization: "Default"
      inventory: "{{ inventory_name }}"
      project: "{{ project_name }}"
      playbook: "job_add_inventory.yml"
      credentials:
        - "CRED-AC-CAC"
      state: "present"
      survey_enabled: yes
      survey_spec: "{{ lookup('file', 'job_add_host_survey.json') }}"