---
- name: configure an Automation Controller
  hosts: localhost
  gather_facts: false
  vars_files: vars.yml
  tasks:
  - name: Add inventory INV-CAC-AC
    ansible.controller.inventory: 
      name: "INV-CAC-AC"
      description: "configure an Automation Controller - Automation Controller"
      organization: "Default"
      state: present

  - name: Add host to inventory INV-CAC-AC
    ansible.controller.host:
      name: "{{ automation_controller_host | default('ansible-1.st8q6.sandbox577.opentlc.com') }}"
      description: "Automation Controller"
      inventory: "INV-CAC-AC"
      state: present
