---
- name: configure an Automation Controller
  hosts: localhost
  gather_facts: false
  collections:
     - ansible.controller
  tasks:
  - name: Add inventory
    inventory: 
      name: "INV-CAC-AC"
      description: "configure an Automation Controller - Automation Controller"
      organization: "Default"
      state: present
