---
- name: restart pool
  hosts: server1
  gather_facts: false
  collections:
    - community.windows
    
  tasks:

   - name: Return information about an existing application pool
     community.windows.win_iis_webapppool:
       name: "{{ apppool }}"
       state: present