---
- name: Add inventory server
  hosts: localhost
  vars:
    server_list: |
  gather_facts: false
  vars_files: vars.yml
  tasks:
  - name: Check existing hosts in AAP inventory
    ansible.controller.host:
      name: "{{ item }}"
      inventory: "IIS_PRD"
    loop: "{{ server_list.splitlines() }}"
    register: check_inventory_result