---
- name: Coletar e Exibir Informações de Memória
  hosts: windows
  gather_facts: yes  # Coletar informações do sistema

  tasks:

    - name: Exibir informações coletadas CPU
      debug:
        msg: "AÇÃO 1 RDP - AÇÃO 2 - w3wp"


    - name: Obter informações de Memória
      win_shell: |
        $memoryInfo = Get-CimInstance -ClassName Win32_OperatingSystem
        $memoryUsed = $memoryInfo.TotalVisibleMemorySize - $memoryInfo.FreePhysicalMemory
        $memoryUsage = [math]::Round(($memoryUsed / $memoryInfo.TotalVisibleMemorySize) * 100, 2)

        $info = @{
          memory_usage_percent = $memoryUsage
        }

        $infoJson = $info | ConvertTo-Json
        Write-Host $infoJson
      register: system_info
      changed_when: false

    - name: Extrair informações de Memória
      set_fact:
        memory_usage_percent: "{{ (system_info.stdout | from_json).memory_usage_percent }}"

    - name: Exibir informações de Memória
      debug:
        var: memory_usage_percent
