---
- name: Exibir status do Site e do Pool de Aplicativos
  hosts: windows
  tasks:
    - name: Obter status do Site
      win_shell: Get-Website -Name "MyWebsite" | Select-Object State
      register: site_status

    - name: Obter status do Pool de Aplicativos
      win_shell: Get-WebAppPoolState -Name "MyAppPool" | Select-Object Value
      register: app_pool_status

    - name: Exibir status do Site
      debug:
        var: site_status.stdout | string | trim

    - name: Exibir status do Pool de Aplicativos
      debug:
        var: app_pool_status.stdout | string | trim