---
- name: List Top 10 CPU and Memory Consuming Processes on Windows
  hosts: windows
  gather_facts: yes
  
  tasks:
    - name: Get Process List
      win_shell: |
        Get-Process | Sort-Object -Property CPU -Descending | Select-Object -First 10 | Format-Table -AutoSize
      register: process_list
      changed_when: false  # Não considere isso como uma alteração

    - name: Display Process List
      debug:
        var: process_list.stdout_lines

    - name: Coletar uso de CPU
      win_shell: |
        $cpu = Get-WmiObject -Class Win32_PerfFormattedData_PerfOS_Processor | Where-Object { $_.Name -eq "_Total" }
        [math]::Round($cpu.PercentProcessorTime, 2)
      register: cpu_usage

    - name: Coletar uso de memória
      win_shell: |
        $mem = Get-WmiObject -Class Win32_OperatingSystem
        $mem.TotalVisibleMemorySize, $mem.FreePhysicalMemory
      register: mem_usage

    - name: Exibir uso de CPU e memória
      debug:
        msg: "CPU Usage: {{ cpu_usage.stdout }}%, Memory Usage: {{ ((mem_usage.stdout[0] - mem_usage.stdout[1]) / mem_usage.stdout[0]) * 100 | round(2) }}%"

