---
- name: List Top 10 CPU and Memory Consuming Processes on Windows
  hosts: windows
  gather_facts: yes
  
  tasks:
    - name: Get Process List
      win_shell: |
        Get-Process | Sort-Object -Property CPU -Descending | Select-Object -First 10 | Format-Table -AutoSize
      register: process_list
      changed_when: false  # Não considere isso como uma alteração

    - name: Display Process List
      debug:
        var: process_list.stdout_lines

    - name: Collect System Facts
      ansible.builtin.setup  # Este módulo coleta informações básicas sobre o sistema.

