---
- name: List Top 10 CPU and Memory Consuming Processes on Windows
  hosts: windows
  gather_facts: yes
  
  tasks:
    - name: Get Process List
      win_shell: |
        Get-Process | Sort-Object -Property CPU -Descending | Select-Object -First 10 | Format-Table -AutoSize
      register: process_list
      changed_when: false  # Não considere isso como uma alteração

    - name: Display Process List
      debug:
        var: process_list.stdout_lines

    - name: Exibir uso de CPU
      win_shell: Get-WmiObject -Class Win32_PerfFormattedData_PerfOS_Processor | Select-Object -Property Name, PercentProcessorTime
      register: cpu_info

    - name: Exibir uso de CPU
      debug:
        var: cpu_info.stdout_lines

    - name: Exibir quantidade de memória disponível
      win_shell: Get-WmiObject -Class Win32_PerfFormattedData_PerfOS_Memory | Select-Object -Property AvailableMBytes
      register: mem_info

    - name: Exibir quantidade de memória disponível
      debug:
        var: mem_info.stdout_lines